### ISSUE TITLE
Fuel Gauge at 0x32

### ISSUE THREAD

**Issue by Ddh012345dhD** [porrey/max1704x#14]
i connect SDA-SDA SCL-SCL 5V-VCC GNG-GND and change I2C address in library 0x36->0x36 but Vsoc =0 and Percent over 100%
![image](https://user-images.githubusercontent.com/54657357/151313582-549eadc1-68fc-46b3-a2ab-a987431b6aec.png)

**Comment by porrey** [comment]
Where did you purchase this from? Some clone devices are have known issues. Take a look at some of the threads on closed issues:

https://github.com/porrey/max1704x/issues/10
https://github.com/porrey/max1704x/issues/11
https://github.com/porrey/max1704x/issues/5
