### ISSUE TITLE
Esp8266 Compilation Error

### ISSUE THREAD

**Issue by BhargavVadaliya** [porrey/max1704x#20]
Example: Max17044
Board: NodeMCU 1.0

Arduino IDE throwing Error when compiling Max17044 example for Esp8266 board.

Error:
"C:\\Users\\TECHNO~1\\AppData\\Local\\Temp\\arduino_build_883167\\libraries\\MAX1704X\\MAX1704X.cpp.o"

C:\Users\TechnoML3\Documents\Arduino\libraries\MAX1704X\src\MAX1704X.cpp: In member function 'bool MAX1704X::begin(uint8_t)':

C:\Users\TechnoML3\Documents\Arduino\libraries\MAX1704X\src\MAX1704X.cpp:70:1: error: no return statement in function returning non-void [-Werror=return-type]

   70 | }

      | ^

cc1plus.exe: some warnings being treated as errors

Using library MAX1704X at version 1.2.7 in folder: C:\Users\TechnoML3\Documents\Arduino\libraries\MAX1704X 

Using library Wire at version 1.0 in folder: C:\Users\TechnoML3\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\Wire 

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by porrey** [comment]
Corrected in v1.2.8
