### ISSUE TITLE
Why read sensor error，What do I do

### ISSUE THREAD

**Issue by anyi-suchuyin** [porrey/max1704x#3]
![360截图20200410210513720](https://user-images.githubusercontent.com/56124203/78993011-49ebd500-7b6f-11ea-82f0-b156e2c0e5f9.jpg)

**Comment by porrey** [comment]
Can you provide more information. Code, circuit diagrams and photos of the circuit would be helpful.

**Comment by porrey** [comment]
This issue could be due to some boards not using address 0x36. A new library version that allows the address to be specified in the constructor. Try address **0x32**.
